language: node_js
node_js:
  - "0.11"
  - "0.10"
script: make test REPORTER=spec

notifications:
  email: false
  slack:
    secure: rt4NQ/57VVaK5hlkySATUD938w+jcnq8tpOseftqqVmGOk5c24tg/0yONgm7PTcKJebx8eJQV/wgfjdCidzmW16lkUcqT+R7/59SajJk7v+rJd3cYc0Qzc4lhlsR/tS0juvt+6kR0N5aUinDwzpvdz4i0Y+TkscBzjL5uWVvlBc=
